Repository witseie-elen4010/2022-group-lab-011, pull requests merged in 2022-05, with the labels that each got.

#61 Dev sync page style
  views/users/game.ejs
Labels: enhancement

#96 game page layout setup for addition of score cards and other info
  public/main.js
  public/styles.css
  views/users/solo_game.ejs
Labels: user-story

#105 Dev selenium tests
  package-lock.json
  package.json
  public/test/test_home.js
  public/test/test_index.js
  public/test/test_login.js
  public/test/tt.html
Labels: developer-sized-story

#109 Dev jest unit tests
  package.json
  public/_tests_/main.test.js
  public/calcScore.js
  public/main.js
Labels: developer-sized-story

#115 Dev game refactor
  package.json
  public/index.html
  public/main.js
  public/styles.css
Labels: developer-sized-story

#117 Refactor and additional tests
  package.json
  public/_tests_/main.test.js
  public/calcScore.js
  public/main.js
Labels: developer-sized-story
